-- M23 — reference_data
-- المرجع: docs/DB_IMPLEMENTATION_SPEC_v1.md §B8، docs/ROLE_PERMISSION_SEED_v1.md §2، §3، §4، §6، §8.1؛
--         docs/AUTHORIZATION_MATRIX_v1.md §4 (الأوصاف)؛ قرار 2026-09-26 (البذر من القوائم الصريحة)
--
-- البيانات المرجعية في migration لا في seed.sql (B8 §8.1) — كي تكون في Production.
--   • 73 permission — الكتالوج المجمَّد (K1–K4). is_sensitive = العمليتان sensitive_read و export (يُلزمان بالتدقيق — DD §2.8، §7.4)
--   • 10 أدوار نظام: platform_tenant_id NULL، is_system، active
--   • role_permissions: القوائم الصريحة في §4؛ group_manager و school_admin بقاعدتي الطرح المنصوص عليهما في §4.2 و§4.3
--   • platform_admin_roles: platform_admin بصلاحياته التسع (§6)
-- بالكود لا بالـUUID (B8 §8.2). سياق service: T6 يترك created_by فارغاً، T7 يسجل system، T8 مُعفى (G7).
-- الأعداد الفعلية: tenant_admin 71, group_manager 62, school_admin 59, secretary 19, accountant 11, teacher 11, counselor 10, bus_supervisor 2, guardian 6, student 4.
-- (عناوين §4 وجدول §5 في الوثيقة كانت متقادمة — صُحِّحت مع هذه الـmigration.)
-- كشف الانحراف: 23_reference_data يثبت كل مجموعة حرفياً — أي اختلاف يُفشل CI.

insert into public.permissions (code, resource, operation, description, is_sensitive) values
  ('academic_year.activate', 'academic_year', 'activate', 'تفعيل سنة', false),
  ('academic_year.close', 'academic_year', 'close', 'إغلاق سنة', false),
  ('academic_year.create', 'academic_year', 'create', 'إنشاء سنة', false),
  ('academic_year.export', 'academic_year', 'export', 'تصدير بيانات السنة', true),
  ('academic_year.read', 'academic_year', 'read', 'قراءة السنة', false),
  ('academic_year.update', 'academic_year', 'update', 'تعديل سنة قبل الإغلاق وفق القيود', false),
  ('audit.read', 'audit', 'read', 'قراءة سجل التدقيق ضمن Scope', false),
  ('audit.sensitive_read', 'audit', 'sensitive_read', 'قراءة أحداث حساسة', true),
  ('enrollment.archive', 'enrollment', 'archive', 'إنهاء/أرشفة التسجيل', false),
  ('enrollment.create', 'enrollment', 'create', 'إنشاء تسجيل', false),
  ('enrollment.export', 'enrollment', 'export', 'تصدير التسجيلات', true),
  ('enrollment.read', 'enrollment', 'read', 'قراءة التسجيل', false),
  ('enrollment.transfer', 'enrollment', 'transfer', 'نقل الطالب', false),
  ('enrollment.update', 'enrollment', 'update', 'تعديل التسجيل ضمن القيود التاريخية', false),
  ('family.read', 'family', 'read', 'قراءة الأسرة', false),
  ('family.update', 'family', 'update', 'تعديل الأسرة', false),
  ('grade_level.manage', 'grade_level', 'manage', 'إدارة الصفوف', false),
  ('grade_level.read', 'grade_level', 'read', 'قراءة الصفوف', false),
  ('group.archive', 'group', 'archive', 'تعطيل/أرشفة Group', false),
  ('group.create', 'group', 'create', 'إنشاء Group', false),
  ('group.export', 'group', 'export', 'تصدير بيانات Group', true),
  ('group.read', 'group', 'read', 'قراءة Group', false),
  ('group.update', 'group', 'update', 'تعديل Group', false),
  ('guardian.create', 'guardian', 'create', 'إنشاء ولي أمر', false),
  ('guardian.export', 'guardian', 'export', 'تصدير بيانات أولياء الأمور', true),
  ('guardian.link', 'guardian', 'link', 'ربط ولي أمر بطالب', false),
  ('guardian.read', 'guardian', 'read', 'قراءة ولي الأمر', false),
  ('guardian.sensitive_read', 'guardian', 'sensitive_read', 'قراءة بيانات حساسة لولي الأمر', true),
  ('guardian.unlink', 'guardian', 'unlink', 'فك الربط وفق الصلاحية', false),
  ('guardian.update', 'guardian', 'update', 'تعديل بيانات ولي الأمر المسموح بها', false),
  ('membership.create', 'membership', 'create', 'إنشاء عضوية', false),
  ('membership.end', 'membership', 'end', 'إنهاء عضوية', false),
  ('membership.read', 'membership', 'read', 'قراءة العضويات', false),
  ('membership.update', 'membership', 'update', 'تعديل عضوية', false),
  ('permission.read', 'permission', 'read', 'قراءة Permission catalog', false),
  ('profile.read', 'profile', 'read', 'قراءة الملف الشخصي الإداري', false),
  ('profile.update', 'profile', 'update', 'تعديل البيانات المسموح بها', false),
  ('role.assign', 'role', 'assign', 'إسناد Role لعضوية', false),
  ('role.create', 'role', 'create', 'إنشاء Role مخصص', false),
  ('role.read', 'role', 'read', 'قراءة الأدوار', false),
  ('role.update', 'role', 'update', 'تعديل Role مخصص', false),
  ('school.archive', 'school', 'archive', 'إغلاق/أرشفة مدرسة', false),
  ('school.create', 'school', 'create', 'إنشاء مدرسة', false),
  ('school.export', 'school', 'export', 'تصدير بيانات المدرسة', true),
  ('school.read', 'school', 'read', 'قراءة مدرسة', false),
  ('school.update', 'school', 'update', 'تعديل إعدادات المدرسة', false),
  ('scope.assign', 'scope', 'assign', 'إسناد/تضييق Scope', false),
  ('section.manage', 'section', 'manage', 'إدارة الشعب', false),
  ('section.read', 'section', 'read', 'قراءة الشعب', false),
  ('security.export', 'security', 'export', 'تصدير سجل أمني', true),
  ('security.manage', 'security', 'manage', 'إدارة إعدادات أمنية محددة', false),
  ('staff.archive', 'staff', 'archive', 'أرشفة موظف', false),
  ('staff.assign', 'staff', 'assign', 'إسناد الموظف إلى مدرسة/تكليف', false),
  ('staff.create', 'staff', 'create', 'إنشاء موظف', false),
  ('staff.export', 'staff', 'export', 'تصدير الموظفين', true),
  ('staff.read', 'staff', 'read', 'قراءة الموظفين', false),
  ('staff.update', 'staff', 'update', 'تعديل موظف', false),
  ('stage.manage', 'stage', 'manage', 'إدارة المراحل', false),
  ('stage.read', 'stage', 'read', 'قراءة المراحل', false),
  ('student.archive', 'student', 'archive', 'أرشفة الطالب', false),
  ('student.create', 'student', 'create', 'إنشاء طالب', false),
  ('student.export', 'student', 'export', 'تصدير بيانات الطلاب', true),
  ('student.read', 'student', 'read', 'قراءة بيانات الطالب', false),
  ('student.sensitive_read', 'student', 'sensitive_read', 'قراءة الحقول المصنفة حساسة', true),
  ('student.transfer', 'student', 'transfer', 'بدء/تنفيذ نقل وفق قواعد النقل', false),
  ('student.update', 'student', 'update', 'تعديل بيانات الطالب', false),
  ('tenant.create', 'tenant', 'create', 'إنشاء Tenant — Platform Admin حصراً (K4)', false),
  ('tenant.export', 'tenant', 'export', 'تصدير بيانات Tenant', true),
  ('tenant.read', 'tenant', 'read', 'قراءة Tenant', false),
  ('tenant.suspend', 'tenant', 'suspend', 'تعليق Tenant — Platform Admin حصراً، لا يُمنح لأي دور Tenant (K3)', false),
  ('tenant.update', 'tenant', 'update', 'تعديل إعدادات Tenant', false),
  ('term.manage', 'term', 'manage', 'إدارة الفصول الدراسية', false),
  ('term.read', 'term', 'read', 'قراءة الفصول الدراسية', false);

insert into public.roles (platform_tenant_id, code, name, is_system, status) values
  (null, 'tenant_admin', 'Tenant Admin', true, 'active'),
  (null, 'group_manager', 'Group Manager', true, 'active'),
  (null, 'school_admin', 'School Admin', true, 'active'),
  (null, 'secretary', 'Secretary', true, 'active'),
  (null, 'accountant', 'Accountant', true, 'active'),
  (null, 'teacher', 'Teacher', true, 'active'),
  (null, 'counselor', 'Counselor', true, 'active'),
  (null, 'bus_supervisor', 'Bus Supervisor', true, 'active'),
  (null, 'guardian', 'Guardian', true, 'active'),
  (null, 'student', 'Student', true, 'active');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from (values
  ('tenant_admin', 'academic_year.activate'),
  ('tenant_admin', 'academic_year.close'),
  ('tenant_admin', 'academic_year.create'),
  ('tenant_admin', 'academic_year.export'),
  ('tenant_admin', 'academic_year.read'),
  ('tenant_admin', 'academic_year.update'),
  ('tenant_admin', 'audit.read'),
  ('tenant_admin', 'audit.sensitive_read'),
  ('tenant_admin', 'enrollment.archive'),
  ('tenant_admin', 'enrollment.create'),
  ('tenant_admin', 'enrollment.export'),
  ('tenant_admin', 'enrollment.read'),
  ('tenant_admin', 'enrollment.transfer'),
  ('tenant_admin', 'enrollment.update'),
  ('tenant_admin', 'family.read'),
  ('tenant_admin', 'family.update'),
  ('tenant_admin', 'grade_level.manage'),
  ('tenant_admin', 'grade_level.read'),
  ('tenant_admin', 'group.archive'),
  ('tenant_admin', 'group.create'),
  ('tenant_admin', 'group.export'),
  ('tenant_admin', 'group.read'),
  ('tenant_admin', 'group.update'),
  ('tenant_admin', 'guardian.create'),
  ('tenant_admin', 'guardian.export'),
  ('tenant_admin', 'guardian.link'),
  ('tenant_admin', 'guardian.read'),
  ('tenant_admin', 'guardian.sensitive_read'),
  ('tenant_admin', 'guardian.unlink'),
  ('tenant_admin', 'guardian.update'),
  ('tenant_admin', 'membership.create'),
  ('tenant_admin', 'membership.end'),
  ('tenant_admin', 'membership.read'),
  ('tenant_admin', 'membership.update'),
  ('tenant_admin', 'permission.read'),
  ('tenant_admin', 'profile.read'),
  ('tenant_admin', 'profile.update'),
  ('tenant_admin', 'role.assign'),
  ('tenant_admin', 'role.create'),
  ('tenant_admin', 'role.read'),
  ('tenant_admin', 'role.update'),
  ('tenant_admin', 'school.archive'),
  ('tenant_admin', 'school.create'),
  ('tenant_admin', 'school.export'),
  ('tenant_admin', 'school.read'),
  ('tenant_admin', 'school.update'),
  ('tenant_admin', 'scope.assign'),
  ('tenant_admin', 'section.manage'),
  ('tenant_admin', 'section.read'),
  ('tenant_admin', 'security.export'),
  ('tenant_admin', 'security.manage'),
  ('tenant_admin', 'staff.archive'),
  ('tenant_admin', 'staff.assign'),
  ('tenant_admin', 'staff.create'),
  ('tenant_admin', 'staff.export'),
  ('tenant_admin', 'staff.read'),
  ('tenant_admin', 'staff.update'),
  ('tenant_admin', 'stage.manage'),
  ('tenant_admin', 'stage.read'),
  ('tenant_admin', 'student.archive'),
  ('tenant_admin', 'student.create'),
  ('tenant_admin', 'student.export'),
  ('tenant_admin', 'student.read'),
  ('tenant_admin', 'student.sensitive_read'),
  ('tenant_admin', 'student.transfer'),
  ('tenant_admin', 'student.update'),
  ('tenant_admin', 'tenant.export'),
  ('tenant_admin', 'tenant.read'),
  ('tenant_admin', 'tenant.update'),
  ('tenant_admin', 'term.manage'),
  ('tenant_admin', 'term.read'),
  ('group_manager', 'academic_year.activate'),
  ('group_manager', 'academic_year.close'),
  ('group_manager', 'academic_year.create'),
  ('group_manager', 'academic_year.export'),
  ('group_manager', 'academic_year.read'),
  ('group_manager', 'academic_year.update'),
  ('group_manager', 'audit.read'),
  ('group_manager', 'audit.sensitive_read'),
  ('group_manager', 'enrollment.archive'),
  ('group_manager', 'enrollment.create'),
  ('group_manager', 'enrollment.export'),
  ('group_manager', 'enrollment.read'),
  ('group_manager', 'enrollment.transfer'),
  ('group_manager', 'enrollment.update'),
  ('group_manager', 'family.read'),
  ('group_manager', 'family.update'),
  ('group_manager', 'grade_level.manage'),
  ('group_manager', 'grade_level.read'),
  ('group_manager', 'group.export'),
  ('group_manager', 'group.read'),
  ('group_manager', 'group.update'),
  ('group_manager', 'guardian.create'),
  ('group_manager', 'guardian.export'),
  ('group_manager', 'guardian.link'),
  ('group_manager', 'guardian.read'),
  ('group_manager', 'guardian.sensitive_read'),
  ('group_manager', 'guardian.unlink'),
  ('group_manager', 'guardian.update'),
  ('group_manager', 'membership.create'),
  ('group_manager', 'membership.end'),
  ('group_manager', 'membership.read'),
  ('group_manager', 'membership.update'),
  ('group_manager', 'permission.read'),
  ('group_manager', 'profile.read'),
  ('group_manager', 'profile.update'),
  ('group_manager', 'role.assign'),
  ('group_manager', 'role.read'),
  ('group_manager', 'school.archive'),
  ('group_manager', 'school.create'),
  ('group_manager', 'school.export'),
  ('group_manager', 'school.read'),
  ('group_manager', 'school.update'),
  ('group_manager', 'scope.assign'),
  ('group_manager', 'section.manage'),
  ('group_manager', 'section.read'),
  ('group_manager', 'staff.archive'),
  ('group_manager', 'staff.assign'),
  ('group_manager', 'staff.create'),
  ('group_manager', 'staff.export'),
  ('group_manager', 'staff.read'),
  ('group_manager', 'staff.update'),
  ('group_manager', 'stage.manage'),
  ('group_manager', 'stage.read'),
  ('group_manager', 'student.archive'),
  ('group_manager', 'student.create'),
  ('group_manager', 'student.export'),
  ('group_manager', 'student.read'),
  ('group_manager', 'student.sensitive_read'),
  ('group_manager', 'student.transfer'),
  ('group_manager', 'student.update'),
  ('group_manager', 'term.manage'),
  ('group_manager', 'term.read'),
  ('school_admin', 'academic_year.activate'),
  ('school_admin', 'academic_year.close'),
  ('school_admin', 'academic_year.create'),
  ('school_admin', 'academic_year.export'),
  ('school_admin', 'academic_year.read'),
  ('school_admin', 'academic_year.update'),
  ('school_admin', 'audit.read'),
  ('school_admin', 'audit.sensitive_read'),
  ('school_admin', 'enrollment.archive'),
  ('school_admin', 'enrollment.create'),
  ('school_admin', 'enrollment.export'),
  ('school_admin', 'enrollment.read'),
  ('school_admin', 'enrollment.transfer'),
  ('school_admin', 'enrollment.update'),
  ('school_admin', 'family.read'),
  ('school_admin', 'family.update'),
  ('school_admin', 'grade_level.manage'),
  ('school_admin', 'grade_level.read'),
  ('school_admin', 'guardian.create'),
  ('school_admin', 'guardian.export'),
  ('school_admin', 'guardian.link'),
  ('school_admin', 'guardian.read'),
  ('school_admin', 'guardian.sensitive_read'),
  ('school_admin', 'guardian.unlink'),
  ('school_admin', 'guardian.update'),
  ('school_admin', 'membership.create'),
  ('school_admin', 'membership.end'),
  ('school_admin', 'membership.read'),
  ('school_admin', 'membership.update'),
  ('school_admin', 'permission.read'),
  ('school_admin', 'profile.read'),
  ('school_admin', 'profile.update'),
  ('school_admin', 'role.assign'),
  ('school_admin', 'role.read'),
  ('school_admin', 'school.export'),
  ('school_admin', 'school.read'),
  ('school_admin', 'school.update'),
  ('school_admin', 'scope.assign'),
  ('school_admin', 'section.manage'),
  ('school_admin', 'section.read'),
  ('school_admin', 'security.export'),
  ('school_admin', 'security.manage'),
  ('school_admin', 'staff.archive'),
  ('school_admin', 'staff.assign'),
  ('school_admin', 'staff.create'),
  ('school_admin', 'staff.export'),
  ('school_admin', 'staff.read'),
  ('school_admin', 'staff.update'),
  ('school_admin', 'stage.manage'),
  ('school_admin', 'stage.read'),
  ('school_admin', 'student.archive'),
  ('school_admin', 'student.create'),
  ('school_admin', 'student.export'),
  ('school_admin', 'student.read'),
  ('school_admin', 'student.sensitive_read'),
  ('school_admin', 'student.transfer'),
  ('school_admin', 'student.update'),
  ('school_admin', 'term.manage'),
  ('school_admin', 'term.read'),
  ('secretary', 'academic_year.read'),
  ('secretary', 'enrollment.create'),
  ('secretary', 'enrollment.read'),
  ('secretary', 'enrollment.update'),
  ('secretary', 'family.read'),
  ('secretary', 'family.update'),
  ('secretary', 'grade_level.read'),
  ('secretary', 'guardian.create'),
  ('secretary', 'guardian.link'),
  ('secretary', 'guardian.read'),
  ('secretary', 'guardian.update'),
  ('secretary', 'profile.read'),
  ('secretary', 'school.read'),
  ('secretary', 'section.read'),
  ('secretary', 'stage.read'),
  ('secretary', 'student.create'),
  ('secretary', 'student.read'),
  ('secretary', 'student.update'),
  ('secretary', 'term.read'),
  ('accountant', 'academic_year.read'),
  ('accountant', 'audit.read'),
  ('accountant', 'enrollment.read'),
  ('accountant', 'family.read'),
  ('accountant', 'grade_level.read'),
  ('accountant', 'guardian.read'),
  ('accountant', 'profile.read'),
  ('accountant', 'school.read'),
  ('accountant', 'section.read'),
  ('accountant', 'staff.read'),
  ('accountant', 'student.read'),
  ('teacher', 'academic_year.read'),
  ('teacher', 'enrollment.read'),
  ('teacher', 'family.read'),
  ('teacher', 'grade_level.read'),
  ('teacher', 'guardian.read'),
  ('teacher', 'profile.read'),
  ('teacher', 'school.read'),
  ('teacher', 'section.read'),
  ('teacher', 'staff.read'),
  ('teacher', 'student.read'),
  ('teacher', 'term.read'),
  ('counselor', 'academic_year.read'),
  ('counselor', 'enrollment.read'),
  ('counselor', 'family.read'),
  ('counselor', 'grade_level.read'),
  ('counselor', 'guardian.read'),
  ('counselor', 'profile.read'),
  ('counselor', 'school.read'),
  ('counselor', 'section.read'),
  ('counselor', 'student.read'),
  ('counselor', 'student.sensitive_read'),
  ('bus_supervisor', 'profile.read'),
  ('bus_supervisor', 'school.read'),
  ('guardian', 'enrollment.read'),
  ('guardian', 'family.read'),
  ('guardian', 'guardian.read'),
  ('guardian', 'profile.read'),
  ('guardian', 'school.read'),
  ('guardian', 'student.read'),
  ('student', 'enrollment.read'),
  ('student', 'profile.read'),
  ('student', 'school.read'),
  ('student', 'student.read')
) as m(role_code, permission_code)
join public.roles r       on r.code = m.role_code and r.platform_tenant_id is null
join public.permissions p on p.code = m.permission_code;

insert into public.platform_admin_roles (code, name, description) values
  ('platform_admin', 'Platform Admin', 'Platform operator — tenant lifecycle and platform-level audit (C3)');

insert into public.platform_admin_role_permissions (platform_admin_role_id, permission_id)
select r.id, p.id
from public.platform_admin_roles r
join public.permissions p on p.code in ('audit.read', 'group.create', 'group.read', 'school.create', 'school.read', 'tenant.create', 'tenant.read', 'tenant.suspend', 'tenant.update')
where r.code = 'platform_admin';

-- حارس داخل الـmigration: يفشل النشر إن خرجت الأعداد عن الوثيقة
do $$
begin
  if (select count(*) from public.permissions) <> 73 then
    raise exception 'M23: expected 73 permissions, got %', (select count(*) from public.permissions);
  end if;
  if (select count(*) from public.roles where is_system) <> 10 then
    raise exception 'M23: expected 10 system roles';
  end if;
  if (select count(*) from public.role_permissions) <> 255 then
    raise exception 'M23: expected 255 role_permissions, got %', (select count(*) from public.role_permissions);
  end if;
  if exists (select 1 from public.role_permissions rp join public.permissions p on p.id = rp.permission_id
             where p.code in ('tenant.suspend', 'tenant.create')) then
    raise exception 'M23: a tenant role holds a platform-only permission (K3/K4, E5)';
  end if;
  if (select count(*) from public.platform_admin_role_permissions) <> 9 then
    raise exception 'M23: expected 9 platform_admin permissions';
  end if;
end $$;
